/**
 * Root Layout Component
 * 
 * Defines the root HTML structure and global providers for the Next.js application.
 * Sets up fonts, global styles, navigation, and background decorations.
 * Includes polyfills for browser compatibility and BigInt JSON serialization.
 */

import type { Metadata } from 'next'
import './globals.css'
import { AppProviders } from '@/components/app-providers'

import React from 'react'
import ClientPolyfills from '@/lazorkit-components/client-pollyfills'
import { Instrument_Serif } from 'next/font/google'
import { AppHeader } from '@/components/app-header'
import { AppFooter } from '@/components/app-footer'
/**
 * Loads Instrument Serif font from Google Fonts
 * Optimized by Next.js for performance with automatic font subsetting
 */
const instrumentSerif = Instrument_Serif({
  weight: '400',
  subsets: ['latin'],
  variable: '--instrument-serif',
})

/**
 * Metadata for the application
 * Used by Next.js for SEO and browser tab information
 */
export const metadata: Metadata = {
  title: 'Lazorkitstarter',
  description: 'Generated by create-solana-dapp',
}

/**
 * Navigation links configuration
 * Defines the main navigation items displayed in the header
 */
export type NavLink = {
  label: string
  href: string
  external?: boolean
  icon: 'docs' | 'github' | 'example' | 'twitter' | 'telegram'
}



/**
 * Navigation links configuration
 */
const links: NavLink[] = [
  {
    label: 'Documentation',
    href: 'https://docs.lazor.sh',
    external: true,
    icon: 'docs',
  },
  {
    label: 'GitHub',
    href: 'https://github.com',
    external: true,
    icon: 'github',
  },
  {
    label: 'Example dApp',
    href: '/',
    icon: 'example',
  },
  {
    label: 'X (Twitter)',
    href: 'https://x.com/lazorkit',
    external: true,
    icon: 'twitter',
  },
  {
    label: 'Telegram',
    href: 'https://t.me/lazorkit',
    external: true,
    icon: 'telegram',
  },
]



/**
 * Root layout component that wraps all pages
 * Provides global structure, providers, and visual decorations
 * 
 * @param children - Page content to be rendered
 */
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${instrumentSerif.variable} antialiased`}>
        <ClientPolyfills />
        <AppProviders>
          {/* Decorative gradient overlays for visual depth */}
          <div className="fixed inset-0 pointer-events-none overflow-hidden">
            <div className="absolute -top-32 -left-32 w-96 h-96 bg-[#7857FF]/5 rounded-full blur-3xl" />
            <div className="absolute -top-32 -right-32 w-80 h-80 bg-[#7857FF]/4 rounded-full blur-3xl" />
            <div className="absolute -bottom-32 -left-32 w-72 h-72 bg-[#7857FF]/3 rounded-full blur-3xl" />
            <div className="absolute -bottom-32 -right-32 w-96 h-96 bg-[#7857FF]/5 rounded-full blur-3xl" />
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-[#7857FF]/2 rounded-full blur-3xl" />
          </div>
          <AppHeader links={links} />
          {/* Main content area with proper z-index layering */}
          <div className="relative z-10">
            {children}
          </div>
          <AppFooter links={links} />
        </AppProviders>
      </body>
    </html>
  )
}

/**
 * Global BigInt JSON serialization patch
 * Allows BigInt values to be serialized with JSON.stringify without errors
 * Required for Solana transaction signatures and large numeric values
 */
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}